server:
  port: 8081
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer 
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:productdb;DB_CLOSE_ON_EXIT=FALSE
#    url: jdbc:mysql://localhost:3306/productdb
#    username: root
#    password: root@123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
#      ddl-auto: update
      ddl-auto: create-drop
  application:
    name: PRODUCT-SERVICE
logging:
  file:
    path: logging
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%15.15t] %-80.80c{1.} : %X : %m%n%ex"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger ---  %X : %msg%n"  
  level:
    org.springframework.web: ERROR
    com.interventure.task: DEBUG
    org.hibernate: ERROR
    org.apache.kafka: ERROR
app:
 kafka:
   producer:
    topic: product-topic
